label_map = {
    'time': 'Time [s]',
    'x_vel_mps': 'X Velocity [m/s]',
    'y_vel_mps': 'Y Velocity [m/s]',
    'z_vel_mps': 'Z Velocity [m/s]',
    'roll_vel_rps': 'Roll Velocity [rad/s]',
    'pitch_vel_rps': 'Pitch Velocity [rad/s]',
    'yaw_vel_rps': 'Yaw Velocity [rad/s]',
    'roll_angle': 'Phi (Roll Angle) [rad]',
    'pitch_angle': 'Theta (Pitch Angle) [rad]',
    'yaw_angle': 'Psi (Yaw Angle) [rad]',
    'x_pos_ned': 'X Position in NED [m]',
    'y_pos_ned': 'Y Position in NED [m]',
    'z_pos_ned': 'Z Position in NED [m]',
    'altitude_m': 'Altitude [m]',
    'speed_of_sound_mps': 'Speed of Sound [m/s]',
    'air_density': 'Air Density [kg/m^3]',
    'mach': 'Mach Number',
    'alpha_rad': 'Angle of Attack [rad]',
    'beta_rad': 'Angle of Sideslip [rad]',
    'true_airspeed_mps': 'True Airspeed [m/s]',
    'c_phi': 'cos(phi)',
    'c_theta': 'cos(theta)',
    'c_psi': 'cos(psi)',
    's_phi': 'sin(phi)',
    's_theta': 'sin(theta)',
    's_psi': 'sin(psi)',
    't_theta': 'tan(theta)',
    'dcm_b2i_11': 'DCM Body to Inertial 11',
    'dcm_b2i_12': 'DCM Body to Inertial 12',
    'dcm_b2i_13': 'DCM Body to Inertial 13',
    'dcm_b2i_21': 'DCM Body to Inertial 21',
    'dcm_b2i_22': 'DCM Body to Inertial 22',
    'dcm_b2i_23': 'DCM Body to Inertial 23',
    'dcm_b2i_31': 'DCM Body to Inertial 31',
    'dcm_b2i_32': 'DCM Body to Inertial 32',
    'dcm_b2i_33': 'DCM Body to Inertial 33',
    'vx_ned_mps': 'X Velocity in NED [m/s]',
    'vy_ned_mps': 'Y Velocity in NED [m/s]',
    'vz_ned_mps': 'Z Velocity in NED [m/s]',
    'roll_dcm_rad': 'Roll Angle from DCM [rad]',
    'pitch_dcm_rad': 'Pitch Angle from DCM [rad]',
    'yaw_dcm_rad': 'Yaw Angle from DCM [rad]'
}